trigger:
- main

pool:
  name: Default

steps:
- script: |
    echo "🚀 Cleaning old files..."

    sudo rm -rf /var/www/html/*

    echo "📂 Copying new files..."

    sudo cp -r * /var/www/html/

    echo "✅ Deployment done"
  displayName: 'Clean and Deploy Website'